/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.utils.Auth;
import com.edusys.utils.MgsBox;
import com.edusys.utils.XImages;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Minh Huy
 */
public class edusys extends javax.swing.JFrame {

    private NhanVienJPanel nhanvienpanel;
    private ChuyenDeJPanel chuyendepanel;
    private NguoiHocJPanel nguoihocpanel;
    private KhoaHocJPanel khoahocpanel;
    private HocVienJPanel hocvienpanel;
    private ThongKeJPanel thongkepanel;
    

    private NhanVienJPanel[] nhanvienarray = new NhanVienJPanel[4];
    int count;
    JButton cd = new JButton();
    JButton kh = new JButton();
    JButton nh = new JButton();
    JButton hv = new JButton();
    JButton tk = new JButton();
    JButton nv = new JButton();

    /**
     * Creates new form edusys
     */
    public edusys() {
        initComponents();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        init();

    }

    void init() {
        this.setIconImage(XImages.getAppIcon());
        new ChaoJDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);
        dangnhapthanhcong();
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");
                String kq = sdf.format(date);
                lblClock.setText(kq);
            }
         
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        btnHuongDan = new javax.swing.JButton();
        tblMainBoard = new javax.swing.JTabbedPane();
        pnlChao = new javax.swing.JPanel();
        lblCHAO = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlStatus = new javax.swing.JPanel();
        lblStatusBar = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniNguoiHoc = new javax.swing.JMenuItem();
        mniChuyenDe = new javax.swing.JMenuItem();
        mniKhoaHoc = new javax.swing.JMenuItem();
        mniHocVien = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniTKNguoiHoc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniTKBangDiem = new javax.swing.JMenuItem();
        mniTKKhoaHoc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniDoanhThu = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        toolBar.setRollover(true);

        btnDangXuat.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-32.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        toolBar.add(btnDangXuat);

        btnKetThuc.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-recycle-bin-32.png"))); // NOI18N
        btnKetThuc.setText("Kết Thúc");
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        toolBar.add(btnKetThuc);
        toolBar.add(jSeparator1);

        btnChuyenDe.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-list-32.png"))); // NOI18N
        btnChuyenDe.setText("Chuyên Đề");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        toolBar.add(btnChuyenDe);

        btnNguoiHoc.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-student-32 (1).png"))); // NOI18N
        btnNguoiHoc.setText("Người Học");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        toolBar.add(btnNguoiHoc);

        btnKhoaHoc.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-certification-32.png"))); // NOI18N
        btnKhoaHoc.setText("Khóa Học");
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        toolBar.add(btnKhoaHoc);

        btnHocVien.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-student-32.png"))); // NOI18N
        btnHocVien.setText("Học Viên");
        btnHocVien.setFocusable(false);
        btnHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocVien.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnHocVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });
        toolBar.add(btnHocVien);

        btnHuongDan.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-globe-32.png"))); // NOI18N
        btnHuongDan.setText("Hướng Dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnHuongDan);

        tblMainBoard.setOpaque(true);

        pnlChao.setBackground(new java.awt.Color(255, 204, 102));

        lblCHAO.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblCHAO.setForeground(new java.awt.Color(102, 102, 255));
        lblCHAO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCHAO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-greeting-48.png"))); // NOI18N
        lblCHAO.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel1.setText("GIẢNG VIÊN");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel2.setText("HỌC VIÊN");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel3.setText("PHỤ HUYNH");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel4.setText("SỰ KIỆN");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fullhd.jpg"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlChaoLayout = new javax.swing.GroupLayout(pnlChao);
        pnlChao.setLayout(pnlChaoLayout);
        pnlChaoLayout.setHorizontalGroup(
            pnlChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(pnlChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlChaoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCHAO, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
        );
        pnlChaoLayout.setVerticalGroup(
            pnlChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlChaoLayout.createSequentialGroup()
                .addGroup(pnlChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChaoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(pnlChaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(pnlChaoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblCHAO, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlChaoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblMainBoard.addTab("TRANG CHỦ", new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-page-24.png")), pnlChao); // NOI18N

        pnlStatus.setBackground(new java.awt.Color(153, 153, 255));

        lblStatusBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Info.png"))); // NOI18N
        lblStatusBar.setText("HỆ QUẢN TRỊ QUẢN TRỊ");

        lblClock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clock.png"))); // NOI18N

        javax.swing.GroupLayout pnlStatusLayout = new javax.swing.GroupLayout(pnlStatus);
        pnlStatus.setLayout(pnlStatusLayout);
        pnlStatusLayout.setHorizontalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLayout.createSequentialGroup()
                .addComponent(lblStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlStatusLayout.setVerticalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addComponent(lblClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuHeThong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuHeThong.setText("HỆ THỐNG");

        mniDangNhap.setText("Đăng Nhập");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangNhap);

        mniDangXuat.setText("Đăng Xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);

        mniDoiMatKhau.setText("Đổi Mật Khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator2);

        mniKetThuc.setText("Kết Thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        menuBar.add(mnuHeThong);

        mnuQuanLy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuQuanLy.setText("QUẢN LÝ");

        mniNguoiHoc.setText("Người Học");
        mniNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoiHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNguoiHoc);

        mniChuyenDe.setText("Chuyên Đề");
        mniChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChuyenDeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniChuyenDe);

        mniKhoaHoc.setText("Khóa Học");
        mniKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoaHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniKhoaHoc);

        mniHocVien.setText("Học Viên");
        mniHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHocVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniHocVien);
        mnuQuanLy.add(jSeparator3);

        mniNhanVien.setText("Quản Trị Viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        menuBar.add(mnuQuanLy);

        mnuThongKe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuThongKe.setText("THỐNG KÊ");

        mniTKNguoiHoc.setText("Người Học Từng Năm");
        mniTKNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKNguoiHocActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKNguoiHoc);
        mnuThongKe.add(jSeparator4);

        mniTKBangDiem.setText("Bảng Điểm Khóa");
        mniTKBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKBangDiemActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKBangDiem);

        mniTKKhoaHoc.setText("Bảng Điểm Từng Khóa");
        mniTKKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKKhoaHocActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKKhoaHoc);
        mnuThongKe.add(jSeparator5);

        mniDoanhThu.setText("Doanh Thu Từng Chuyên Đề");
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhThu);

        menuBar.add(mnuThongKe);

        mnuTroGiup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuTroGiup.setText("TRỢ GIÚP");

        mniHuongDan.setText("Hướng Dẫn Sử Dụng");
        mniHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongDanActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniHuongDan);
        mnuTroGiup.add(jSeparator6);

        mniGioiThieu.setText("Giới Thiệu Sản Phẩm");
        mnuTroGiup.add(mniGioiThieu);

        menuBar.add(mnuTroGiup);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tblMainBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 1546, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblMainBoard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoiHocActionPerformed
        // TODO add your handling code here:
        btnNguoiHocActionPerformed(evt);
        
    }//GEN-LAST:event_mniNguoiHocActionPerformed

    private void mniHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongDanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniHuongDanActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
//           
            if (nhanvienpanel == null) {
                nhanvienpanel = new NhanVienJPanel();
                ImageIcon icon = new ImageIcon(getClass().getResource("/images/Users.png"));
                tblMainBoard.addTab("Quản lý nhân viên", icon, nhanvienpanel, "Quản lý nhân viên");
                nv.setSize(60, 30);
                nv.setHorizontalAlignment(JButton.CENTER);
                Border bd = BorderFactory
                        .createEtchedBorder(EtchedBorder.RAISED);
                nv.setBorder(bd);
                nv.setLocation(1450, 5);

                ImageIcon ic = new ImageIcon(getClass().getResource("/images/icons8-close-32.png"));
                nv.setIcon(ic);
                nv.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        closeNV();
                    }
                });
                nhanvienpanel.add(nv);
            }
            tblMainBoard.setSelectedComponent(nhanvienpanel);
        } else {
            MgsBox.Alert(this, "Bạn chưa đăng nhập");
        }
    }//GEN-LAST:event_mniNhanVienActionPerformed
    void closeNV() {
        tblMainBoard.remove(nhanvienpanel);
        nhanvienpanel = null;
    }
    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            if (chuyendepanel == null) {
                chuyendepanel = new ChuyenDeJPanel();
                cd.setSize(60, 30);
                cd.setHorizontalAlignment(JButton.CENTER);
                Border bd = BorderFactory
                        .createEtchedBorder(EtchedBorder.RAISED);
                cd.setBorder(bd);
                cd.setLocation(1450, 9);

                ImageIcon ic = new ImageIcon(getClass().getResource("/images/icons8-close-32.png"));
                cd.setIcon(ic);
                cd.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        closeCD();
                    }
                });
                chuyendepanel.add(cd);

                ImageIcon icon = new ImageIcon(getClass().getResource("/images/icons8-wish-list-24.png"));
                tblMainBoard.addTab("Quản lý chuyên đề", icon, chuyendepanel, "Quản lý chuyên đề");
            }

            tblMainBoard.setSelectedComponent(chuyendepanel);
        } else {
            MgsBox.Alert(this, "Bạn chưa đăng nhập");
        }
    }//GEN-LAST:event_btnChuyenDeActionPerformed
    void closeCD() {
        tblMainBoard.remove(chuyendepanel);
        chuyendepanel = null;
    }
    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            if (nguoihocpanel == null) {
                nguoihocpanel = new NguoiHocJPanel();
                nh.setSize(60, 30);
                nh.setHorizontalAlignment(JButton.CENTER);
                Border bd = BorderFactory
                        .createEtchedBorder(EtchedBorder.RAISED);
                nh.setBorder(bd);
                nh.setLocation(1450, 5);

                ImageIcon ic = new ImageIcon(getClass().getResource("/images/icons8-close-32.png"));
                nh.setIcon(ic);
                nh.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        closeNH();
                    }

                });
                nguoihocpanel.add(nh);

                ImageIcon icon = new ImageIcon(getClass().getResource("/images/icons8-student-24.png"));
                tblMainBoard.addTab("Quản lý người học", icon, nguoihocpanel, "Quản lý người học");
            }

            tblMainBoard.setSelectedComponent(nguoihocpanel);
        } else {
            MgsBox.Alert(this, "Bạn chưa đăng nhập");
        }

    }//GEN-LAST:event_btnNguoiHocActionPerformed
    void closeNH() {
        tblMainBoard.remove(nguoihocpanel);
        nguoihocpanel = null;
    }
    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            if (khoahocpanel == null) {
                khoahocpanel = new KhoaHocJPanel();
                kh.setSize(60, 30);
                kh.setHorizontalAlignment(JButton.CENTER);
                Border bd = BorderFactory
                        .createEtchedBorder(EtchedBorder.RAISED);
                kh.setBorder(bd);
                kh.setLocation(1450, 5);

                ImageIcon ic = new ImageIcon(getClass().getResource("/images/icons8-close-32.png"));
                kh.setIcon(ic);
                kh.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        closeKH();
                    }

                });
                khoahocpanel.add(kh);
                ImageIcon icon = new ImageIcon(getClass().getResource("/images/icons8-google-classroom-24.png"));
                tblMainBoard.addTab("Quản lý khóa học", icon, khoahocpanel, "Quản lý khóa học");
            }

            tblMainBoard.setSelectedComponent(khoahocpanel);
        } else {
            MgsBox.Alert(this, "Bạn chưa đăng nhập");
        }
    }//GEN-LAST:event_btnKhoaHocActionPerformed
    void closeKH() {
        tblMainBoard.remove(khoahocpanel);
        khoahocpanel = null;
    }
    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            if (hocvienpanel == null) {
                hocvienpanel = new HocVienJPanel();
                hv.setSize(60, 30);
                hv.setHorizontalAlignment(JButton.CENTER);
                Border bd = BorderFactory
                        .createEtchedBorder(EtchedBorder.RAISED);
                hv.setBorder(bd);
                hv.setLocation(1450, 5);

                ImageIcon ic = new ImageIcon(getClass().getResource("/images/icons8-close-32.png"));
                hv.setIcon(ic);
                hv.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        closeHV();
                    }

                });
                hocvienpanel.add(hv);

                ImageIcon icon = new ImageIcon(getClass().getResource("/images/icons8-hocvien-24.png"));
                tblMainBoard.addTab("Quản lý học viên", icon, hocvienpanel, "Quản lý học viên");
            }

            tblMainBoard.setSelectedComponent(hocvienpanel);
        } else {
            MgsBox.Alert(this, "Bạn chưa đăng nhập");
        }
    }//GEN-LAST:event_btnHocVienActionPerformed
    void closeHV() {
        tblMainBoard.remove(hocvienpanel);
        hocvienpanel = null;
    }
    private void mniTKBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKBangDiemActionPerformed
        // TODO add your handling code here:
        openDoanhThu(0);
    }//GEN-LAST:event_mniTKBangDiemActionPerformed

    private void mniTKNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKNguoiHocActionPerformed
        // TODO add your handling code here:
        openDoanhThu(1);
    }//GEN-LAST:event_mniTKNguoiHocActionPerformed

    private void mniTKKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKKhoaHocActionPerformed
        // TODO add your handling code here:
        openDoanhThu(2);
    }//GEN-LAST:event_mniTKKhoaHocActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        // TODO add your handling code here:
        openDoanhThu(3);
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKetThucActionPerformed
    private void dangXuat() {
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;
        }

        tblMainBoard.remove(nhanvienpanel);
        tblMainBoard.remove(chuyendepanel);
        tblMainBoard.remove(khoahocpanel);
        tblMainBoard.remove(hocvienpanel);
        tblMainBoard.remove(nguoihocpanel);
        tblMainBoard.remove(thongkepanel);

        nhanvienpanel = null;
        chuyendepanel = null;
        khoahocpanel = null;
        hocvienpanel = null;
        nguoihocpanel = null;
        thongkepanel = null;
        Auth.clear();
        lblCHAO.setText("");
        new DangNhapJDialog(this, true).setVisible(true);
        dangnhapthanhcong();
    }
    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        dangXuat();

    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed
    private void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhauJDialog(this, true).setVisible(true);
        } else {
            MgsBox.Alert(this, "Vui lòng đăng nhập ");
        }
    }
    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
        openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChuyenDeActionPerformed
        // TODO add your handling code here:
        btnChuyenDeActionPerformed(evt);
    }//GEN-LAST:event_mniChuyenDeActionPerformed

    private void mniKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoaHocActionPerformed
        // TODO add your handling code here:
        btnKhoaHocActionPerformed(evt);
    }//GEN-LAST:event_mniKhoaHocActionPerformed

    private void mniHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHocVienActionPerformed
        // TODO add your handling code here:
        btnHocVienActionPerformed(evt);
    }//GEN-LAST:event_mniHocVienActionPerformed
    private void dangnhapthanhcong() {
        lblCHAO.setText("Welcome " + Auth.user.getMaNV() + ":))");
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        dangnhapthanhcong();
    }//GEN-LAST:event_formWindowOpened
    void openDoanhThu(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MgsBox.Alert(this, "Bạn không có quyền xem doanh thu");
                thongkepanel.setDelete();
            } else if (index != 3 && !Auth.isManager()) {
                if (thongkepanel == null) {
                    thongkepanel = new ThongKeJPanel();
                    ImageIcon icon = new ImageIcon(getClass().getResource("/images/icons8-chart-24.png"));
                    tblMainBoard.addTab("Quản lý thống kê", icon, thongkepanel, "Quản lý thống kê");
                    tk.setSize(60, 30);
                    tk.setHorizontalAlignment(JButton.CENTER);
                    Border bd = BorderFactory
                            .createEtchedBorder(EtchedBorder.RAISED);
                    tk.setBorder(bd);
                    tk.setLocation(1450, 5);

                    ImageIcon ic = new ImageIcon(getClass().getResource("/images/icons8-close-32.png"));
                    tk.setIcon(ic);
                    tk.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            closeDT();
                        }

                    });
                    thongkepanel.add(tk);
                }
                thongkepanel.setDelete();
                tblMainBoard.setSelectedComponent(thongkepanel);
                thongkepanel.selectTab(index);

            } else if (Auth.isManager()) {
                if (thongkepanel == null) {
                    thongkepanel = new ThongKeJPanel();
                    ImageIcon icon = new ImageIcon(getClass().getResource("/images/icons8-chart-24.png"));
                    tblMainBoard.addTab("Quản lý thống kê", icon, thongkepanel, "Quản lý thống kê");
                    tk.setSize(60, 30);
                    tk.setHorizontalAlignment(JButton.CENTER);
                    Border bd = BorderFactory
                            .createEtchedBorder(EtchedBorder.RAISED);
                    tk.setBorder(bd);
                    tk.setLocation(1450, 5);

                    ImageIcon ic = new ImageIcon(getClass().getResource("/images/icons8-close-32.png"));
                    tk.setIcon(ic);
                    tk.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            closeDT();
                        }

                    });
                    thongkepanel.add(tk);
                }

                tblMainBoard.setSelectedComponent(thongkepanel);
                thongkepanel.selectTab(index);
            }

        } else {
            MgsBox.Alert(this, "Vui lòng đăng nhập");
        }
    }

    void closeDT() {
        tblMainBoard.remove(thongkepanel);
        thongkepanel = null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edusys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edusys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edusys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edusys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edusys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblCHAO;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblStatusBar;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mniChuyenDe;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHocVien;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniKhoaHoc;
    private javax.swing.JMenuItem mniNguoiHoc;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniTKBangDiem;
    private javax.swing.JMenuItem mniTKKhoaHoc;
    private javax.swing.JMenuItem mniTKNguoiHoc;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPanel pnlChao;
    private javax.swing.JPanel pnlStatus;
    private javax.swing.JTabbedPane tblMainBoard;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
